packages:
  - packages/linea-ens-app
  - packages/linea-ens-subgraph

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - next
  - '@next/env'

overrides:
  '@sentry/browser@<7.119.1': '>=7.119.1'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  ejs@<3.1.10: '>=3.1.10'
  elliptic@<6.5.6: '>=6.5.6'
  elliptic@<6.6.0: '>=6.6.0'
  elliptic@<=6.6.0: '>=6.6.1'
  elliptic@>=2.0.0 <=6.5.6: '>=6.5.7'
  elliptic@>=4.0.0 <=6.5.6: '>=6.5.7'
  elliptic@>=5.2.1 <=6.5.6: '>=6.5.7'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  parse-duration@<2.1.3: '>=2.1.3'
  playwright@<1.55.1: '>=1.55.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  rollup@<2.79.2: '>=2.79.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
  tar-fs@>=3.0.0 <3.0.7: '>=3.0.7'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tar@<6.2.1: '>=6.2.1'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  ws@>=2.1.0 <5.2.4: '>=5.2.4'
  ws@>=7.0.0 <7.5.10: '>=7.5.10'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
  yargs-parser@<=5.0.0: '>=5.0.1'
