packages:
  - packages/linea-state-verifier
  - packages/linea-ccip-gateway
  - packages/linea-ens-resolver
  - packages/linea-ens-app
  - packages/linea-ens-subgraph
  - packages/poh-signer-api

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - next

overrides:
  '@openzeppelin/contracts@>=4.5.0 <4.9.6': '>=4.9.6'
  '@sentry/browser@<7.119.1': '>=7.119.1'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  braces@<3.0.3: '>=3.0.3'
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  ejs@<3.1.10: '>=3.1.10'
  elliptic@<6.5.6: '>=6.5.6'
  elliptic@<6.6.0: '>=6.6.0'
  elliptic@<=6.6.0: '>=6.6.1'
  elliptic@>=2.0.0 <=6.5.6: '>=6.5.7'
  elliptic@>=4.0.0 <=6.5.6: '>=6.5.7'
  elliptic@>=5.2.1 <=6.5.6: '>=6.5.7'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  micromatch@<4.0.8: '>=4.0.8'
  min-document@<=2.19.0: '>=2.19.1'
  next: '15.4.10'
  node-forge@<1.3.2: '>=1.3.2'
  node-notifier@<8.0.1: '>=8.0.1'
  parse-duration@<2.1.3: '>=2.1.3'
  playwright@<1.55.1: '>=1.55.1'
  postcss@<8.4.31: '>=8.4.31'
  rollup@<2.79.2: '>=2.79.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
  tar-fs@<1.16.6: '>=1.16.6'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar-fs@>=3.0.0 <3.0.7: '>=3.0.7'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tar@<6.2.1: '>=6.2.1'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  ws@>=2.1.0 <5.2.4: '>=5.2.4'
  ws@>=7.0.0 <7.5.10: '>=7.5.10'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
  yargs-parser@<=5.0.0: '>=5.0.1'
