name: Run linea-ccip-gateway tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/linea-ccip-gateway/**"
      - ".github/workflows/linea-ccip-gateway-tests.yml"
  push:
    branches:
      - main
    paths:
      - "packages/linea-ccip-gateway/**"
      - ".github/workflows/linea-ccip-gateway-tests.yml"

jobs:
  linea-ccip-gateway-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/linea-ccip-gateway
            packages/linea-state-verifier
            pnpm-workspace.yaml
            pnpm-lock.yaml
            package.json
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 10.10.0

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile contract
        run: pnpm --filter linea-ccip-gateway compile

      - name: Run tests
        run: pnpm --filter linea-ccip-gateway test
