name: Run linea-ccip-gateway tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/linea-ccip-gateway/**"
      - ".github/workflows/linea-ccip-gateway-tests.yml"
  push:
    branches:
      - main
    paths:
      - "packages/linea-ccip-gateway/**"
      - ".github/workflows/linea-ccip-gateway-tests.yml"

jobs:
  linea-ccip-gateway-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/linea-ccip-gateway
            packages/linea-state-verifier
            pnpm-workspace.yaml
            pnpm-lock.yaml
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.1.3

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: For act to work (local testing)
        run: npm -g install yarn

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile contract
        run: pnpm --filter linea-ccip-gateway compile

      - name: Run tests
        run: pnpm --filter linea-ccip-gateway test
