name: "Build and Publish PoH Verifier API"

on:
  push:
    branches:
      - main
    paths:
      - "packages/poh-verifier/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/poh-verifier/**"
  release:
    types:
      - released

jobs:
  poh-verifier-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Docker Tag
        id: docker-tag
        if: ${{ github.event_name != 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)-poh-verifier" | tee $GITHUB_ENV

      - name: Set Docker Tag - Release
        id: docker-tag-release
        if: ${{ github.event_name == 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)-poh-verifier-${GITHUB_REF#refs/tags/}" | tee $GITHUB_ENV

      - name: Login to Docker Repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Image Build and Publish
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ENV_FILE=.env.production
            SIGNER_PRIVATE_KEY=${{ secrets.POH_VERIFIER_PRIVATE_KEY }}
          context: ./packages/poh-verifier
          file: ./packages/poh-verifier/Dockerfile
          push: true
          tags: consensys/linea-resolver:${{ env.DOCKER_TAG }}
