name: MetaMask Security Code Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      SECURITY_SCAN_METRICS_TOKEN:
        required: false
      APPSEC_BOT_SLACK_WEBHOOK:
        required: false
  workflow_dispatch:

jobs:
  run-security-scan:
    name: Run security scan
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Analyse code
        uses: MetaMask/action-security-code-scanner@v1
        with:
          repo: ${{ github.repository }}
          paths_ignored: |
            'services/web3signer'
            '**/test*/**'
            '**/*.test.*'
            '**/*.spec.*'
            '**/*.sol'
            '**/e2e/**'
            '**/node_modules/**'
          project_metrics_token: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
          slack_webhook: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}
