name: Slither Analysis
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          target: 'packages/contracts'
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}